# .readthedocs.yaml

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

projects:
  - name: dist_emaj
    path: docs/en
    configuration: docs/en/conf.py
    language: en

  - name: dist_emaj-french
    path: docs/fr
    configuration: docs/fr/conf.py
    language: fr

