#! /usr/bin/perl -w
#
# check_error_messages.pl
#
# This perl script extracts error or warning messages from the dist_emaj--devel.sql source file.
# It then extracts the error or warning messages from the regression tests result files,
# and finaly displays the messages from the source file that are not covered by the regression tests.

use warnings; use strict;

# The 3 variables below are to be customized
  my $dir = "/home/postgres/proj/dist_emaj";
  my $ficSrc = $dir . "/sql/dist_emaj--devel.sql";
  my $dirOut = $dir . "/test/18/results";

# Variables used to process the source code
  my $line;
  my $lineNumber = 0;
  my $lineNumberInFnct = 0;
  my $schema;
  my $fnctName;
  my $msgType;
  my $msg;
  my %msgs = ();
  my %msgRegexp = ();
  my %msgCount = ();
  my $nbException = 0;
  my $nbWarning = 0;
  my $regexp;

# Variables used to process the regression test output results
  my $res;
  my $script;
  my $fnctId;
  my $nbFound;
  my $lastFound;
  my $isTittleDisplayed = 0;

# Initialisation
  print ("------------------------------------------------------------\n");
  print ("  Analysis of error messages generated by regression tests  \n");
  print ("------------------------------------------------------------\n");
  open (FICSRC, $ficSrc) || die ("Error in opening " . $ficSrc . " file\n");

#
# Phase 1.
#
  print "-> Reading the extension source file ($ficSrc)...\n";
# Scan and process input file
  while (<FICSRC>){
    $line = $_; $lineNumber++; $lineNumberInFnct++;
# Delete the comment part of the line, if any (this does not properly process -- pattern inside literal of object names, but this is enough for now)
    $line =~ s/--.*//;
# Detection of function or do block start
    if ($line =~ /^CREATE OR REPLACE FUNCTION\s+(.*?)\.(.*?)\(/) {
      $schema = $1; $fnctName = $2; $lineNumberInFnct = 1;
    }
    if ($line =~ /^DO /) {
      $schema = ''; $fnctName = 'do'; $lineNumberInFnct = 1;
    }
# Detection of warning or error messages
    if ($line =~ /RAISE (EXCEPTION|WARNING)\s+'\s*(.*?)'(\s|;|,)/) {
      $msgType = $1; $msg = $2;
      next if ($msg eq '');
      $nbException++ if ($msgType eq 'EXCEPTION');
      $nbWarning++ if ($msgType eq 'WARNING');
# Transform the message into a regexp
#   (add a \ before '.', '(', and ')' characters; replace double single quotes by a unique one and % characters by '.*?')
      $regexp = $msg;
      $regexp =~ s/\./\\\./g;
      $regexp =~ s/\(/\\\(/g;
      $regexp =~ s/\)/\\\)/g;
      $regexp =~ s/''/'/g;
      $regexp =~ s/%/.*?/g;
# Register the message and its regexp
      if ($fnctName eq 'do') {
        $msgs{"$fnctName:$lineNumber"} = "$msgType:$msg";
        $msgRegexp{"$fnctName:$lineNumber"} = "$msgType:$regexp";
        $msgCount{"$fnctName:$lineNumber"} = 0;
      } else {
        $msgs{"$schema.$fnctName:$lineNumberInFnct"} = "$msgType:$msg";
        $msgRegexp{"$schema.$fnctName:$lineNumberInFnct"} = "$msgType:$regexp";
        $msgCount{"$schema.$fnctName:$lineNumberInFnct"} = 0;
      }
    }
  }

# Complete the source processing
  print "The source file contains $nbException exceptions and $nbWarning warning messages.\n";
  close (FICSRC);

#
# Phase 2.
#
  print "-> Reading the test output files from $dirOut...\n";
# Search for error messages in regression tests results, using grep
  $res = `grep -P 'ERROR:|WARNING:' $dirOut/*.out`;

# Split the output into lines for analysis
  $msg = '';
  while ($res =~ /^(.+?)\n(.*)/sm) {
    $line = $1;
    $res = $2;
# Get interresting pieces from each line
    if ($line =~ /^.*\/(.+?)\.out:.*?(ERROR|WARNING):\s*(\S.*)/) {        # line ERROR or WARNING
# An interesting line is identified
      $script = $1 . '.sql';
      $msgType = $2;
      $msg = $3;
###      if ($1 ne 'beforeMigLoggingGroup' && $1 ne 'install_previous' && $1 ne 'install_upgrade' && $1 !~ /psql/i) {
#### Ignore lines from the scripts that process code from the previous E-Maj version
        if ($msgType eq 'ERROR' || $msgType eq 'WARNING') {
          $nbFound = 0;
# Look for this message in the recorded messages from the source
          while (($fnctId, $regexp) = each(%msgRegexp)) {
            if (($msgType eq 'ERROR' && ("EXCEPTION:" . $msg) =~ $regexp) || ($msgType eq 'WARNING' && ("WARNING:" . $msg) =~ $regexp)) {
              $nbFound++;
              $lastFound = $fnctId;
            }
          }
          if ($nbFound > 1) {
            print "!!! In script $script, the message '$msg' has been found at several ($nbFound) places in the source\n";
          }
          if ($nbFound >= 1) {
# At least one place in the source fit the message read from the regression tests output, so increment usage counter (of the last found, if several)
            $msgCount{"$lastFound"}++;
          }
        }
###      }
    } else {
      if ($line !~ /^.*\/(.+?)\.out:\\!(.*)/) {     # lines with \! (shell command calls) are not processed
# Unexpected problem with the line analysis
        die "Unrecognized line:\n$line\n";
      }
    }
  }

# The analysis of regression test output files is completed, display the results
  while (($fnctId, $nbFound) = each(%msgCount)) {
    if ($nbFound == 0) {
# Do not report some messages known to not be present in the regression test suite
                            # installation conditions that are not met during the tests
      if ($msgs{$fnctId} ne 'EXCEPTION:Distributed E-Maj installation: The current postgres version (%) is too old for this dist_emaj version. '
       && $msgs{$fnctId} !~ 'EXCEPTION:_verify_server \(\d+\): %'
                            # extension drop conditions that are not met during the tests
       && $msgs{$fnctId} ne 'EXCEPTION:dist_emaj_drop_extension: The role executing this function must be a superuser.'
       && $msgs{$fnctId} ne 'WARNING:dist_emaj_drop_extension: The dist_emaj_viewer role has not been dropped (sqlstate %).'
       && $msgs{$fnctId} ne 'WARNING:dist_emaj_drop_extension: The dist_emaj_adm role has not been dropped (sqlstate %).'
                            # error messages that cannot be encountered (error already trapped earlier)
       && $msgs{$fnctId} ne 'EXCEPTION:_check_dist_mark: The cluster "%" is unknown.'
       && $msgs{$fnctId} ne 'EXCEPTION:_check_dist_mark: Cannot perform a distributed rollback for an empty cluster.'
         ) {
# Report the other messages
        if (! $isTittleDisplayed) {
          print "The coded error/warning messages not found in regression test outputs:\n";
          $isTittleDisplayed = 1;
        }
        print "  Id = $fnctId ; message = $msgs{$fnctId}\n";
      }
    }
  }
  if (! $isTittleDisplayed) {
    print "No unexpected uncovered error or warning messages\n";
  }
  print "Analysis completed.\n"

# End of the script
